name: Package and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Extrae el código fuente del repositorio

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Configura la versión de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Actualiza pip
          pip install setuptools wheel  # Instala dependencias necesarias para el empaquetado
          # Instala dependencias adicionales desde requirements.txt si existe
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel  # Empaqueta el proyecto en formato distribuible

      # Diagnóstico: Verificar el contenido del directorio actual
      - name: List files in project directory
        run: |
          echo "Listando archivos en la raíz del proyecto..."
          ls -R .

      # Diagnóstico: Verificar el contenido de la carpeta src
      - name: List files in src directory
        run: |
          echo "Listando archivos en la carpeta src/..."
          ls -R src

      # Verificar la existencia de la carpeta dist/ y listar su contenido
      - name: List files in dist directory
        run: |
          echo "Verificando la existencia de la carpeta dist/..."
          if [ -d "./dist" ]; then
            echo "dist/ directory exists. Listando su contenido:"
            ls -R dist
          else
            echo "La carpeta dist/ no existe o está vacía."
          fi

      # Intentar crear la carpeta dist/ si no existe y mostrar mensaje
      - name: Verify dist folder creation
        run: |
          if [ -d "./dist" ]; then
            echo "dist/ directory already exists."
          else
            echo "dist/ directory does not exist. Creating it now."
            mkdir dist
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}  # Token para autenticar la acción
        with:
          tag_name: v${{ github.run_number }}  # Crea un tag basado en el número de ejecución
          release_name: "Word Guessing Game - Release ${{ github.run_number }}"  # Nombre de la versión
          body: |
            ## Cambios en esta versión
            - Empaquetado del juego completo.
            - Añadido sistema de pistas limitadas.
            - Verificación de victoria y derrota con mensajes claros.
          draft: false  # Publica el release inmediatamente
          prerelease: false  # No es una versión preliminar

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}  # Token para autenticar la acción
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # URL para subir los archivos
          asset_path: ./dist/*  # Ruta de los archivos empaquetados
          asset_name: "word-guessing-game-v${{ github.run_number }}.tar.gz"  # Nombre del archivo a subir
          asset_content_type: application/gzip  # Tipo de contenido del archivo
